export const mockPosts = [
  {
    id: '1',
    author: {
      id: 'user1',
      name: 'Alice Chen',
      handle: 'alicechen',
      avatar: '/woman-with-camera.png',
      isVerified: true,
    },
    content: 'Just captured this amazing sunset at the beach. The golden hour never disappoints!',
    image: '/sunset-beach-golden-hour.jpg',
    timestamp: '2 hours ago',
    likes: 1240,
    comments: 89,
    shares: 45,
    liked: false,
    authenticity: {
      isVerified: true,
      nautilusScore: 98,
      sealValid: true,
    },
  },
  {
    id: '2',
    author: {
      id: 'user2',
      name: 'Marcus Johnson',
      handle: 'marcusj',
      avatar: '/smiling-man-portrait.png',
      isVerified: true,
    },
    content: 'New blog post about sustainable living is now live! Check it out if you\'re interested in making a difference.',
    image: '/sustainable-eco-living.png',
    timestamp: '4 hours ago',
    likes: 856,
    comments: 124,
    shares: 234,
    liked: false,
    authenticity: {
      isVerified: true,
      nautilusScore: 95,
      sealValid: true,
    },
  },
  {
    id: '3',
    author: {
      id: 'user3',
      name: 'Sofia Patel',
      handle: 'sofiapatel',
      avatar: '/woman-artist-creative.jpg',
      isVerified: false,
    },
    content: 'Working on a new art project combining digital and traditional media. Excited to share the final result soon!',
    image: '/digital-art-creative-painting.jpg',
    timestamp: '6 hours ago',
    likes: 542,
    comments: 67,
    shares: 23,
    liked: false,
    authenticity: {
      isVerified: false,
    },
  },
  {
    id: '4',
    author: {
      id: 'user4',
      name: 'James Wilson',
      handle: 'jameswilson',
      avatar: '/man-professional-tech.jpg',
      isVerified: true,
    },
    content: 'Just launched our new open-source project! Happy to contribute to the developer community. Star us on GitHub!',
    image: '/computer-code-programming-open-source.jpg',
    timestamp: '8 hours ago',
    likes: 1089,
    comments: 203,
    shares: 412,
    liked: false,
    authenticity: {
      isVerified: true,
      nautilusScore: 97,
      sealValid: true,
    },
  },
  {
    id: '5',
    author: {
      id: 'user5',
      name: 'Emma Rodriguez',
      handle: 'emmarod',
      avatar: '/woman-outdoor-adventure.jpg',
      isVerified: true,
    },
    content: 'Mountain hiking season is here! Nothing beats fresh air and amazing views. Who else is a hiking enthusiast?',
    image: '/mountain-hiking-nature-trail.jpg',
    timestamp: '12 hours ago',
    likes: 2156,
    comments: 445,
    shares: 178,
    liked: false,
    authenticity: {
      isVerified: true,
      nautilusScore: 99,
      sealValid: true,
    },
  },
]
